package com.romagmir.biketrack.activities

import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import androidx.preference.Preference
import androidx.preference.PreferenceFragmentCompat
import com.romagmir.biketrack.R
import com.romagmir.biketrack.ui.NumberPickerPreference
import com.romagmir.biketrack.ui.NumberPickerPreferenceDialog

/**
 * Used to handle the app settings.
 *
 * This activity is mostly autogenerated by Android Studio
 */
class SettingsActivity : AppCompatActivity() {
    /**
     * Perform initialization of all fragments.
     *
     * @param savedInstanceState If the activity is being re-initialized after
     *     previously being shut down then this Bundle contains the data it most
     *     recently supplied in [onSaveInstanceState].
     */
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.settings_activity)
        if (savedInstanceState == null) {
            supportFragmentManager
                .beginTransaction()
                .replace(R.id.settings, SettingsFragment())
                .commit()
        }
        // Enable the "back arrow" on the toolbar to go back to the previous activity
        setSupportActionBar(findViewById(R.id.toolbar))
        supportActionBar?.setDisplayHomeAsUpEnabled(true)
    }

    class SettingsFragment : PreferenceFragmentCompat() {
        override fun onCreatePreferences(savedInstanceState: Bundle?, rootKey: String?) {
            setPreferencesFromResource(R.xml.root_preferences, rootKey)
        }

        override fun onDisplayPreferenceDialog(preference: Preference?) {
            if (parentFragmentManager.findFragmentByTag(DIALOG_FRAGMENT_TAG) != null) {
                return
            }

            if (preference is NumberPickerPreference) {
                // Display [NumberPickerPreferenceDialog]
                val dialog = NumberPickerPreferenceDialog.newInstance(preference.key)
                dialog.setTargetFragment(this, 0)
                dialog.show(parentFragmentManager, DIALOG_FRAGMENT_TAG)
            } else {
                super.onDisplayPreferenceDialog(preference)
            }
        }

        companion object {
            /** Dialog used by the [NumberPickerPreferenceDialog][com.romagmir.biketrack.ui.NumberPickerPreferenceDialog] fragment */
            private const val DIALOG_FRAGMENT_TAG = "NumberPickerDialog"
        }
    }
}